### ISSUE TITLE
According htop 977M, but 1024 has been defined

### ISSUE THREAD

**Issue by 030** [kamaln7/ansible-swapfile#11] opened 2016-09-15 07:50 UTC
```
swapfile_size: 1024MB
```

**Comment by damoon** [comment] 2016-11-24 13:55
i can reproduce this.
you need to write 1024MiB instead of 1024MB.

**Comment by kamaln7** [comment] 2016-12-03 20:32
This seems to be simply a matter of using the right units. Correct me if I'm wrong, of course, but I'm closing this for now :)

**Closed by kamaln7** 2016-12-03 20:32 UTC

**Comment by 030** [comment] 2017-01-12 10:18
the MiB works
